### ISSUE TITLE
Avoid including sandbox startup time when measuring time usage

### ISSUE THREAD

**Issue by cairomassimo** [turingarena/turingarena#13]
For example, let the sandbox announce when it is ready, so that we can subtract the initialization time.
One solution could be to make the sandbox send a `SIGSTOP` to itself (if possible) so that we can `wait(..., WUNTRACED)` for it from outside.
At the moment, a call to `sleep` is made to ensure the sandbox is settled before measuring time.

**Comment by cairomax** [comment]
Sending `SIGSTOP` to self can be done only before actually entering in the sandbox. Maybe make the solutions write `0` to `stdout` when they are ready to receive input. When we read this `0`, we are sure that the sandbox is settled and we can start measuring time. Still, one could do some work (say, in static constructors) before the `0` is printed, but this work has to be independent from input. We may well allow it anyways: the result of this work could be computed offline and hardcoded in the source file itself!.
