### ISSUE TITLE
Consider dropping support for global variables

### ISSUE THREAD

**Issue by cairomax** [turingarena/turingarena#17]
Global variables functionality can always be simulated by an extra function call at the beginning.

Pros of global variables:

- avoid an extra function to be defined
- avoid ugly statements like `::N = N` in solutions, only to copy a parameter to global scope
- having global variables may be easier for the solution writer

Cons:

- need to keep the supporting code in the core
- complicate the API (they are not positional, but passed by key, etc.)
- in languages like Python, the sandbox is required to run the solution code only after executing `init` (and in general, the translation of the `init` block is non-trivial)
- the solution is forced to use the provided data structures (i.e., plain arrays) to represent the data in the global scope (if they use their own, they lose any advantage of having our global variables in the first place)
- the problem writer has to choose between two equivalent ways of defining the interface (global variables vs an extra function)
- an extra initialization function is often needed anyways, so that the solutions can pre-process the global variables as they wish
- global variables preclude the possibility to use a different translation for parameters and local variables (say, local variables are not exposed to solutions, so they could always be translated as `int`s, and be converted on-demand to type-safe data types only when passed to functions - however, there are also the callback parameters/return value that have to be taken into account...)

**Comment by alerighi** [comment]
I agree with removing global variables

**Comment by cairomax** [comment]
The current position is to remove global variables *as a way to pass data to the solution*.

However, at the moment they are essential for the callback mechanism, since they are the only way to control the behavior of the body of a callback (besides the arguments).
Before dropping global variables, we need to decide carefully how much control to allow in the callback body.

Here is a proposal of the strong requirements we could set for the interface language:

- there should not be more communication blocks than strictly necessary (i.e., no unnecessary `flush`es)
- non-constant-size data should not be sent redundantly

for all the rest it is more a matter of taste and elegance.

**Comment by cairomax** [comment]
The new interface language drops global variables *and* global callback implementations, in favor of per-function callbacks declarations (i.e., passed as arguments as, say, function pointers) with local, lambda/capture-like implementation in the main block, thus solving most of the above issues.
Moreover, the main block contains only non-reentrant code, making the implementation much simpler.
