### ISSUE TITLE
turingarena command -h

### ISSUE THREAD

**Issue by romeorizzi** [turingarena/turingarena#31]
Attualmente, tolte stringhe non pertinenti a questo issue, funziona così:

> turingarena validate -h
Validate interface file

    Usage:
        validate [options]

    Options:
        -I --interface=<file>  Interface definition file [default: interface.txt].

Mentre lo usage corretto dovrebbe essere:

    Usage:
        turingarena validate [options]

Lo stesso vale anche per gli altri comandi, come template --> turingarena template

**Comment by alerighi** [comment]
I close this issue because it's relative to the old legacy cli, in the new cli there is proper help
