### ISSUE TITLE
Allow declaring callbacks which can never return

### ISSUE THREAD

**Issue by cairomassimo** [turingarena/turingarena#35]

**Comment by cairomax** [comment]
Say:
```
procedure find_the_result() callbacks {
   exitpoint here_is_the_result(result);
}
```

A callback marked as `exitpoint` always terminates the process, without an explicit `exit` instruction in its implementation.

No further work should be needed in the evaluator. For example, in python, the `InterfaceExit` exception is automatically raised after the callback is invoked, and it is caught and dropped in the `with algorithm.run()` block.

**Comment by alerighi** [comment]
It is always possible to kill the process inside a callback implementation.
