### ISSUE TITLE
Running locally the skeleton and solution in python is complicated

### ISSUE THREAD

**Issue by cairomassimo** [turingarena/turingarena#37]
It is currently necessary to rename the solution as `_source.py`.

**Comment by cairomax** [comment]
The skeleton code should be kept as simple as possible.

Thus, the best option is to add a separated `runner.py` module, to be invoked as follows:
```
python runner.py skeleton.py source.py
```
or
```
./runner.py skeleton.py source.py
```

**Comment by cairomassimo** [comment]
Thanks to a main block generated within the skeleton, it is now possible to run the solution with
```
python skeleton.py source.py
```
Closing.
