### ISSUE TITLE
Create a temporary directory for each evaluation

### ISSUE THREAD

**Issue by cairomax** [turingarena/turingarena#42]
The path of this directory should be available in an environment variable.
It should be automatically created and deleted (i.e., not a responsibility of the evaluator).

**Comment by alerighi** [comment]
A temporary directory is create by the evaluator and the path is available to the evaluator in the environment variable `TEMPORARY_DIRECTORY`. 

There is also a field in the `turingarena` package to access that, `turingarena.temporary_directory`.
