### ISSUE TITLE
Can't import random in python solutions

### ISSUE THREAD

**Issue by SartoRiccardo** [turingarena/turingarena#54]
For testing, I put it as the first line of `solution.py` in `sum_of_two_numbers` and this popped up:
```
invalid literal for int() with base 10: '0.052995999999999995'Traceback (most recent call last):
  File "/usr/local/turingarena/backend/turingarena_impl/driver/languages/python/sandbox.py", line 45, in <module>
  File "/usr/local/turingarena/backend/turingarena_impl/driver/languages/python/sandbox.py", line 40, in main
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'random'
```
Which is pretty weird since random is a preinstalled module

**Comment by alerighi** [comment]
Currently, the python sandbox doesn't allow importing other modules.

There is already an issue discussing the possibility to specify in a configuration file the modules that are allowed to be imported in python: #21 

For now, I added random to the modules that gets imported by default in the python sandbox so you can use it.
